# Generated by Django 6.0.5 on 2026-05-26 02:57
# Initial migration — creates all core tables with custom db_table names:
#   - user_profiles (role-based access)
#   - empleados (employee directory)
#   - asistencia (attendance records)
#   - nominas (payroll records)
#   - configuracion_nomina (payroll config)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNomina',
            fields=[
                ('idConfiguracion', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_deduccion', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('bono_fijo', models.DecimalField(decimal_places=2, default=120.0, max_digits=10)),
                ('fecha_vigencia', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'configuracion_nomina',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('puesto', models.CharField(default='Colaborador', max_length=150)),
                ('correo_corporativo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estatus', models.CharField(default='Activo', max_length=50)),
                ('foto_perfil', models.FileField(blank=True, null=True, upload_to='foto_perfil/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='A Tiempo', max_length=50)),
                ('empleado', models.ForeignKey(db_column='idEmpleado', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='empleados.empleado')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('idNomina', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldo_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(db_column='idEmpleado', on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='empleados.empleado')),
            ],
            options={
                'db_table': 'nominas',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(default='empleado', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
